### ISSUE TITLE
Too many empty output and took too long to get the results

### ISSUE THREAD

**Issue by baitian752** [SamuelYvon/netifaces-2#14]
OS: Windows 11
Python Version: 3.11.2

![image](https://user-images.githubusercontent.com/28034106/220538129-aedb3149-5d2b-4b78-bc81-8cdb8a9108cb.png)

**Comment by SamuelYvon** [comment]
Are you using the windows draft fork?

**Comment by SamuelYvon** [comment]
From the readme:
>1.1 What is not working right-now
 >   The gateways API is only working if your system has a /proc/net/route file
 >   The windows API is non-functional

I will try to finish the windows api on monday; no hard promises ;)

**Comment by SamuelYvon** [comment]
@baitian752 Can you test with the latest code on the windows pull request and let me know how it goes? Thanks :)

**Comment by baitian752** [comment]
@SamuelYvon I use the new `win-support` branch, which looks like OK. Thanks for your work.

I install it with `pip install git+https://github.com/SamuelYvon/netifaces-2.git@win-support`

![image](https://user-images.githubusercontent.com/28034106/222184547-e7a8e410-cea3-4d91-a7d4-3954eebde010.png)

**Comment by SamuelYvon** [comment]
Perfect!
