### ISSUE TITLE
Type information mismatch

### ISSUE THREAD

**Issue by dries007** [SamuelYvon/netifaces-2#16]
In the rust library the netmask is called "mask" and so it's passed to Python that way, but the Python type definition has  `Literal["netmask"]` instead.

I propose you change `Literal["netmask"]` to `Literal["mask"]` to not break existing scripts, thanks.

(This is a deviation from the old netifaces package BTW)

**Comment by SamuelYvon** [comment]
Thanks for the catch. Will fix ASAP

**Comment by SamuelYvon** [comment]
I do not think it breaks anything however, it's only the wrong type definition (albeit confusing)

**Comment by dries007** [comment]
No, it works perfectly well, but PyCharm complains about the key not exsiting and I don't like squiggly lines under my code :smile:

**Comment by SamuelYvon** [comment]
> I don't like squiggly lines under my code

That makes two of us ;)
