### ISSUE TITLE
Is ipv6 not implemented?

### ISSUE THREAD

**Issue by B17C0D3** [SamuelYvon/netifaces-2#17]
my test provides only the ipv4 gateway.
the old netifaces also returned the ipv6 gateway

```
import netifaces
print(netifaces.gateways())
{<InterfaceType.AF_INET: 2>: [('192.168.10.1', 'eth0', True)]}
```
also instead of `<InterfaceType.AF_INET: 2>` should be a simple `2` like in the return of 
```
print(netifaces.ifaddresses('eth0'))
{2: [{'addr': '192.168.10.4', 'broadcast': '192.168.10.255', 'mask': '255.255.255.0'}],... and so on
```

i clearly have an ipv6 default route
```
ip -6 route
default via fe80::1eed:6fff:fe2d:91b4 dev eth0 proto ra metric 202 mtu 1492 pref medium
```

**Comment by SamuelYvon** [comment]
It should be working. What's your platform?

**Comment by B17C0D3** [comment]
raspberry os
$ uname -a
Linux cm4 6.1.34-v8+ #1657 SMP PREEMPT Fri Jun 16 12:36:29 BST 2023 aarch64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

**Comment by SamuelYvon** [comment]
Ok; I've spotted why IPv6 gateways are not displayed. Can you confirm whether `ifaddresses(ifname)` returns ipv6 addresses? It works fine here -- might be a platform issue.

I'll fix this soon.

**Comment by B17C0D3** [comment]
yes ifaddresses(ifname) works fine

**Comment by SamuelYvon** [comment]
If you would be so kind, this run https://github.com/SamuelYvon/netifaces-2/actions/runs/5364836999 should provide wheels with the fix.

Here is what I changed:
- I now use `/usr/sbin/ip` if available to get routes, including IPv6. This means if you don't have `ip` on your system, this won't work. The real solution is to get the routes from the kernel, but I don't have time right now to go mess with the rust layer.
- I added an option to get the dictionary keys by integer value. To get the output as you want, you will need to do:
  ```python
   netifaces.gateways(old_api=True)
   ```

Please let me now if this works as expected. I do not have an Ipv6 gateway and am too lazy to make a fake network 😉 This is a straightforward enough change however. If this works, I'll push to pypi.
