### ISSUE TITLE
Please provide precompiled package for python 3.11

### ISSUE THREAD

**Issue by neoclust** [SamuelYvon/netifaces-2#19]
Hello,

to install on windows  w/o the need of installing all the visual studio stuffs, can you provide precompiled whl packages for python 3.10/3.11 when you release a version ?

**Comment by SamuelYvon** [comment]
Odd, it should already be on the build task. Will look into it.

**Comment by SamuelYvon** [comment]
Seems like everything is working fine:

```txt
C:\Users\syvon>"C:\Users\syvon\AppData\Local\Programs\Python\Python311\Scripts\pip.exe" install netifaces2
  Collecting netifaces2
  Downloading netifaces2-0.0.18-cp37-abi3-win_amd64.whl (128 kB)
  ---------------------------------------- 128.7/128.7 kB 2.5 MB/s eta 0:00:00
  Collecting typing-extensions (from netifaces2)
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
  Installing collected packages: typing-extensions, netifaces2
  Successfully installed netifaces2-0.0.18 typing-extensions-4.7.1 
```
It is then usable fine in a python 3.11 shell. 

Are you potentially installing via the package this one is trying to replace (ie, install `netifaces` instead of `netifaces2`?)

**Comment by SamuelYvon** [comment]
You have not commented in a week, and it seems to be working. I'll close, but feel free to re-open if I am missing something.
