### ISSUE TITLE
Logging settings should not be changed on import

### ISSUE THREAD

**Issue by bmerry** [SamuelYvon/netifaces-2#20]
netifaces2 calls `logging.basicConfig` on import [here](https://github.com/SamuelYvon/netifaces-2/blob/c26f428fb8b36f23995608d6c6d5362687adfb20/netifaces/__init__.py#L124). That will interfere with log setup by the application. Note that `logging.basicConfig` does nothing the second time it is called, so if an application uses `logging.basicConfig` for its own logging setup and switches from netifaces to netifaces2, it will silently break the logging setup.

**Comment by SamuelYvon** [comment]
You are correct. Fixing

**Comment by SamuelYvon** [comment]
Fixed in `>=0.0.19`.

Thanks for reporting!
